### ISSUE TITLE
Ashley Valent: Monads don't compose. Free ones do

### ISSUE THREAD

**Issue by avalent** [scalasyd/scalasyd#10]
In the April ScalaSyd meetup Jed talked about Free monads and how they are used in the aws-scala library to abstract away most of the complexity. This covered material from the first part of Runar's excellent talk https://www.parleys.com/tutorial/composable-application-architecture-reasonably-priced-monads

I could talk about the second part which covers composing different algebras using monad coproducts. 

I can only speak at the May meetup because I'll be moving to America in late May.

**Comment by arnolddevos** [comment]
I think this should be an interesting talk. But some critical evaluation of Runar's method would be a welcome inclusion.   

For example, if you follow the method outlined in his presentation you end up with a non-tail-recursive evaluator (ie Runar's foldMap here  https://gist.github.com/runarorama/a8fab38e473fafa0921d will blow the stack ).  

The answer is to use scalaz Free, but that is a more complex beast than the version of Free that Runar presents.  You may need FreeC - Free with Coyoneda.  You are likely to need scalaz Task too.  So instead of a technique we are being sold a framework.

Another concern is the complexity of this approach compared to alternatives.  If we don't actually have a  requirement to compose several algebras the solution could be reduced to one GADT representing the instruction algebra plus an executor to run it.    We can still have multiple executors and testing opportunities just as before.  

Sorry this turned into a bit of a rant.  Intended in an honest spirit of inquiry.
- Arnold

**Comment by avalent** [comment]
Of course, it is important to critically evaluate any technique before using it.

While I don't know for certain I believe that Runar's example of Free was written for simplicity so it can be more easily understood. I don't think it was ever meant to be a production ready implementation like the one in scalaz so I don't think it is fair to hold that against the technique. Scala has limitations (like every language) that must be worked around, and a library like scalaz will do this for you, but understanding trampolining isn't specifically required to understand Free, it is just an implementation detail.

You are correct, FreeC does need to be used. I don't know why you say you will likely need scalaz Task too. You need a natural transformation from your algebra to some monad - yes scalaz Task is a monad but so is Id, and a 1000 others. If you do want to use scalaz Task because it achieves your goals then great, I don't see that as an issue. I consider libraries and frameworks very different beasts, and scalaz is just a library (as opposed to frameworks such as spring and play). This technique may also be implemented from scratch without any libraries, but as you mentioned you need to be careful to avoid blowing the stack.

This technique does introduce complexity versus using only a single algebra, but it has the advantage of separating concerns (key value stores from logging etc) and allows reuse of interpreters. If you write a DynamoDB interpreter for a key value store algebra then it would be nice to reuse this in multiple projects. I don't think interpreters are quite as easy to write as many would have you believe, so reusing a tried and tested interpreter is appealing.

There is always a tradeoff - in many cases I'm sure it makes sense to have only one algebra. Otherwise, there is a way to compose algebras and that is what I plan to present. 

Ashley

**Comment by arnolddevos** [comment]
Well, I take your points except that I am more pessimistic than you about achieving the benefits reuse, whether of algebras or interpreters.  But that is just an opinion.   I don't have any worked-out alternative idea of how to achieve composition of algebras (and their interpreters).
